tests/combine_index_dag_test.py

I made some dumb errors. This fixes them.

fixing python local imports for test "no module found" error

---

Pipfile
Pipfile.lock
dev_combine_index_dag.py
funcake_villanova_dag.py
prod_combine_index_dag.py
tests/combine_index_dag_test.py
tests/conftest.py

- Update funcake dev/prod dags to use the new json variables
- Add first pass skeleton for villanova harvest

Add Villanova harvest

---

funcake_villanova_dag.py
scripts/transform.sh
tests/combine_index_dag_test.py
tests/conftest.py
tests/villanova_dag_test.py

Add task to apply xslt transform and push transformations to s3.
REF FUNCAKE-138

Add transform task.

---

dev_combine_index_dag.py
prod_combine_index_dag.py
scripts/index.sh
tests/conftest.py

- Update index script to use the presign url
- Update syntax to use what other dags have
- Add empty to string when solr auth is not present so that task doesn't error out
- Refactor solr-related variables to use json format

Index script update

---

Pipfile
Pipfile.lock
funcake_villanova_dag.py
scripts/index.sh
scripts/transform.sh
tests/villanova_dag_test.py

~Requires https://github.com/tulibraries/tulflow/pull/23~
What this PR does:
- Adds post-transform Schematron-based filtering & validation step
- Proposing handling XSLT github file retrievals in same way we handle them for schematron Github file retrievals
- (wip) expand tests

Adding schematron function, updating XSLT vars

---

funcake_villanova_dag.py
tests/villanova_dag_test.py

Parameterize XSLT files and branches

---

funcake_free_library_of_philadelphia_dag.py
funcake_villanova_dag.py
tests/free_library_test.py

- Adds dag and tests for Free Library of Philadelphia
- Removes csv tasks from Villanova dag

Create dag for free library of philadelphia

---

dev_combine_index_dag.py
funcake_free_library_of_philadelphia_dag.py
funcake_villanova_dag.py
prod_combine_index_dag.py
scripts/csv_to_xml.py

- Change owner to dpla
- Add schematron variables to csv dag
- Use report prefix for invalid.csv file

Cleanup work on dags

---

.circleci/config.yml
Pipfile
Pipfile.lock
funcake_villanova_dag.py
tests/villanova_dag_test.py

Based on work in https://github.com/tulibraries/tulflow/pull/27

Adds templated task to run collection refresh

---

funcake_dplah_dag.py
funcake_free_library_of_philadelphia_dag.py
funcake_historic_pitt_dag.py
funcake_temple_dag.py
funcake_villanova_dag.py
task_slack_posts.py
variables.json

for @bibliotechy : context matters between being called within a Task / Operator context & a DAG callable context. Hence the slack posts change.

fix slack tasks context, solr vars consistency

---

funcake_dplah_dag.py
funcake_free_library_of_philadelphia_dag.py
funcake_historic_pitt_dag.py
funcake_temple_dag.py
funcake_villanova_dag.py
scripts/batch-transform.xsl
scripts/transform.sh

Needs a write up for discussion of how this changes the batch handling.

revert XSL transform task to bash, batch, record id work-around

---

README.md
funcake_dplah_dag.py
funcake_free_library_of_philadelphia_dag.py
funcake_historic_pitt_dag.py
funcake_temple_dag.py
funcake_villanova_dag.py
variables.json

* update variables.json to match Airflow Prod UI
* Lookup dag specific *_TARGET_ALIAS_ENV

Merge QA changes into prod

---

variables.json

Adds variables for Penn State DAG

update variables.json to add penn state

---

variables.json

I thought I also created a dag. Maybe not.

updated variables file to include uscranton

---

funcake_dags/scripts/transform.sh

Updates airflow-docker-dev-setup submodule to reference release 0.0.1

Adds logging to Transform task bash script

---

funcake_dags/scripts/index.sh
funcake_dags/scripts/publishe_task_report.rb

Iterates over the publish task output and collects all processed record
counts and outputs the total as a JSON string
```json
{ "published": 250 }
```

FLYPIE-201 Add report to publish task.

---

funcake_dags/template.py
funcake_dags/template_dag.py

Fix wrong directory.

---

funcake_dags/scripts/index.sh

cat contents of file instead of echo-ing the file name.

FLYPIE-201 Fix publish task report.

---

variables.json

Will need to have namespace PR in aggregator_mdx merged before this one will work

added variables for penn walters csv

---

funcake_dags/field_counter.py

REF: https://stackoverflow.com/a/11850445/256854

Fix field counter breaks with huge XML files.

---

funcake_dags/template.py

* 'False' is truthy, should be False.
Also fixes typo in config key extraction.

Fix excluded sets typo and type.

---

funcake_dags/scripts/transform.sh

* set -aux to see each bash line echoed before running.
* pass -t to saxon command to get trace... verobse version of command.

Make transform script more verbose

---

tests/field_counter_test.py

Make sure to test that missing fields are reported.

FLYPIE-174: Add better field count test

---

.circleci/config.yml

Changes to airflow playbook require this change

Update prod deploy config to use master branch

---

.circleci/config.yml

Remove deployment to airflow stage in preparation of removing airflow
stage.

BL-1205: Remove stage deploy

---

variables.json

Add new Historic Pittsburgh collections to variable

update HP variables for new collections

---

funcake_dags/template_dag.py
variables.json

I'm adding the Susquehanna dag, even though the Omeka transform has not been done yet (you'll see that variable is empty). There's something weird going on with the setSpecs in http://pahistoryharvest.com/oai-pmh-repository/request, so I want to test the Airflow harvest to see if it pulls records from all the required sets. 
Also, made a small correction to the FandM variables.

Added preliminary Susquehanna dag

---

variables.json

- Add ursinus_fraktur collection to Ursinus harvest config
- Fix duplicate target alias env for F&M and Susqu

Add new Ursinus collection to variables

---

funcake_dags/template_dag.py
variables.json

Not sure why my previous commit from another PR is showing up, but hopefully that shouldn't cause any issues...

Added CHRC dag id and variables

---

funcake_dags/template_dag.py
variables.json

- Add new dag for Drexel Westphal
- Add variables for Drexel Westphal

create dag for drexel westphal

---

variables.json

- add new setspecs to variables.json for Historic Pittsburgh new collections

add new hp collections

---

funcake_dags/template.py

- also updates default branch name to main

Remove default value for xsl_filename

---

funcake_dags/scripts/transform.sh

- Adds a conditional statement to exit with a failure if an XSL_FILENAME variable is not set or is set to only a directory

FLYPIE-258 no false successes in transform task

---

funcake_dags/dev_combine_index_dag.py
funcake_dags/prod_combine_index_dag.py
tests/conftest.py
variables.json

- Updates replication factor to 4
- Updates airflow-docker-dev submodule to latest commit

DEVO-319 Replication factor

---

Pipfile
Pipfile.lock

- Include all packages as dev dependencies

DEVO-37 Package management

---

variables.json

- change pitt_collection.357 to pitt_collection.327

Update incorrect Pitt setSpec

---

variables.json

Update Pitt collections for March 2022 harvest

PD-384 update Pitt variables

---

variables.json

- Update variables to add new collections for Historic Pittsburgh and University of Pittsburgh for June 2022 DPLA harvest

PD-390 HP-Pitt update variables

---

variables.json

- Fix typo in HP and Pitt setspecs

fix typo for HP and Pitt new collections

---

variables.json

- Add new HP/Pitt collections for Sept. 2022 harvest

PD-405 new HP/Pitt collections

---

funcake_dags/template_dag.py

add new docpitt dag

---

variables.json

- add new Pitt collection for March 2023 harvest

add new pitt collection

---

variables.json

PD-448 Add new collection for PHS

---

variables.json

- Add 4 new Pitt collections for December 2023 harvest

Pitt new collections

---

variables.json

- 4 new Pitt collections for special January 2024 harvest

pd-479 new Pitt collections

---

variables.json

New HP/Pitt collections for March 2024 harvest

pd-484 new HP/Pitt collections

---

.circleci/config.yml
.gitignore
.gitmodules
Makefile
Pipfile
Pipfile.lock
README.md

This PR will make circle builds fail if a dependency is added that does not match airflow-constraints.

Automatically check against airflow constraints in circle.

---

variables.json

- add collection:AYA
- add collection:Pacific+War+Postcards

New Lafayette sets for December 2024 harvest
