tulibraries/funcake_dags

.circleci/config.yml, combine_index_dag.py, tests/combine_index_dag_test.py
turns out circleci doesn't name the directory where our repo is cloned the repo name; it is just called project, so funcake_dags import fails.
=> Circleci import

scripts/index.sh
When we `source ~/.bashrc`, it in turn runs `source /etc/bashrc` which throws an error `PS1: unbound variable` 
Other ingest scripts source first and then `set -e` to fail on errors, which seems like a sensible appaorch since we don't actually care about `$PS1`
=> Source bashrc first

funcake_dplah_dag.py, funcake_free_library_of_philadelphia_dag.py, funcake_historic_pitt_dag.py, funcake_temple_dag.py, funcake_villanova_dag.py
Currently all using the generic TARGET_ALIAS_ENV which is not defined,
and thus all are always defaulting to dev
=> Lookup dag specific *_TARGET_ALIAS_ENV

Makefile, funcake_dags/funcake_westchester_dag.py, funcake_dags/template.py, funcake_dags/template_dag.py, tests/template_test.py
Adds a new `funcake_dags/template_dag.py` that can generate funcake dags
dynamically from supplied dag_ids array.
* Generates funcake dags from supplied `dag_ids` array.
* Chooses the correct harvesting task between oai endpoints or csv
* Namespaces the dag_id with "funcake_"
=> FLYPIE-196 Add funcake template dag

funcake_dags/template_dag.py
The airflow webserver only parses files that it determines have dags defined by looking for the airflow.DAG method.  If a file does not import this method, it does not get parsed in the initial airflow-webserver setup, and even if dags are being defined behind a layer of abstraction, they will not show up on the airflow dashboard.
=> Fix template dag not parsed.

funcake_dags/field_counter.py, funcake_dags/scripts/index.sh
* Allow field report to accept dag or other context type variables.
* Do not use undefined variable in publish script.
=> Fix field report and publish task.

funcake_dags/scripts/index.sh
Redirect all output not just standard output for cob_index/traject.
The output that we want to parse is not in the standard output so we
need to redirect all of it in order to parse it correctly.
=> FLYPIE-201 Redirect all output to file.

funcake_dags/scripts/csv_to_xml.py, tests/csv_to_xml_test.py
When we transform csv to xml, if the field is empty in the xml it is
still counted in the field count report.
This commit updates the csv to xml script to skip adding fields that are
empty to the xml.
=> FLYPIE-174: Do not add empty fields to xml from csv.

funcake_dags/field_counter.py, tests/field_counter_test.py
* Instead of `title` uses `{http://purl.org/dc/elements/1.1/}title` for
example.
=> FLYPIE-223 Add namespaces to field count report fields.

.circleci/config.yml
- This means that each change to a repo does not run the entire airflow playbook, but only the parts that update dags. Needs to run the jumphost role so it can connect.
=> DEVO-114 Limit CD to only deploy dags

funcake_dags/template_dag.py
There already seems to be a dag id for lasalle_cdm. I will label the new bepress dag id lasalle_bepress.
=> Added dag id for La Salle BePress repository

variables.json
For new contributor trial run. I used historicpitt.xsl, b/c that's an Islandora repo, right? Let me know if I should swap in a different transform for the initial dag run.
=> Updated variables file to include Franklin and Marshall

variables.json
What this PR does:
- Update variables.json to use historicpitt_static.xsl for aps_static dag
(Note: already tested this by changing variable manually in the Airflow UI and confirmed it works)
=> Update variables to test aps_static

variables.json
Updates include new Islandora transform and switch to oai_dc prefix, which includes required URLs in Islandora OAI endpoint.
=> Updated FandM variables

funcake_dags/scripts/transform.sh
This may fix issue of failure when we process the empty file. Looks like
the actual failure happens when we try to push the "processed" file up
to s3. So, skipping that should fix issue.
=> Skip processing empty files.

funcake_dags/scripts/transform.sh
Reverts tulibraries/funcake_dags#330
Reverting because it doesn't look like this fixes issue. Even though from log it looks like script gets upto the count step without error, it still fails. It would probably require downloading the xml file locally and processing it locally instead of via URL.
=> Revert "Skip processing empty files."

variables.json
ingest_dc_reqd_fields.sch is no longer in the aggregator_mdx repository and was causing the dag to fail.
=> Update TJU East Falls schematron filter

Pipfile, Pipfile.lock
- The newer version has breaking changes, so this needs to be pinned for now
=> Pin cryptography to 3.3.2

variables.json
This collection is being withdrawn from papd repository.
=> Remove papd_shswp-bfp from setSpec list

funcake_dags/scripts/transform.sh
The record count that this script is calculates is wrong when multiple
dags run because there is no distinction being made to distinguish files
belonging to one dag vs another one.
This changes fixes the issue by appending the `$DAG_ID` value to each of
these files.
=> FLYPIE-268: Fix incorrect unique record count.

funcake_dags/scripts/transform.sh
I missed labeling one of the tmp files with $DAG_ID.  This commit adds
it.
=> FLYPIE-268: Fix incorrect unique count for multiple dag runs.

variables.json
- Remove duplicate of pitt_collection.154, which was being harvested twice
=> Remove duplicate setspec from Historic Pittsburgh variables

funcake_dags/scripts/index.sh
Nokogiri is failing to run due to missing library.
This change forces it to use ruby instead of native library.
=> Force ruby platform for bundle install.
